---
# Beats for ARM are currently only available via nightly builds, not repositories
# http://ict.renevdmark.nl/2016/07/05/elastic-beats-on-raspberry-pi/
# Or, how to compile from source
# https://michaelblouin.ca/blog/2016/02/05/build-and-run-beats-on-raspberry-pi/

- name: Makes sure Filebeat installation directory exists
  file: 
    path: /opt/filebeat 
    state: directory
    mode: 0755

- name: Makes sure Filebeat config directory exists
  file: 
    path: /etc/filebeat 
    state: directory
    mode: 0755

- name: Check if Filebeat already downloaded
  stat: 
    path: /opt/filebeat/filebeat-linux-arm
  register: filebeat_st

- name: Download Filebeat
  get_url:
    url: https://beats-nightlies.s3.amazonaws.com/jenkins/filebeat/1458-08da7d97bba4d82ffaa199dee2c83d02b1084059/filebeat-linux-arm
    dest: /opt/filebeat/filebeat-linux-arm
    mode: 0555
  when: filebeat_st.stat.exists is defined and not filebeat_st.stat.exists

- name: Copy Filebeat configuration file
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0744

- name: Creating Filebeat systemd service definition
  template:
    src: filebeat.service
    dest: /lib/systemd/system/filebeat.service
    owner: root
    group: root
    mode: 0744

- name: Starting Filebeat service
  systemd:
    name: filebeat
    enabled: yes
    state: restarted