---
- name: Check if Logstash is already installed
  command: dpkg-query -W logstash
  register: logstash_check_deb
  failed_when: logstash_check_deb.rc > 1
  changed_when: logstash_check_deb.rc == 1

- name: Update repositories cache and install Logstash
  apt:
    name: logstash
    update_cache: yes

# Creating directories for SSL
- name: Creates SSL directories
  file:
    path: /etc/pki/tls/certs
    state: directory

- name: Creates SSL directories
  file:
    path: /etc/pki/tls/private
    state: directory

- name: Updating the config file to restrict outside access
  lineinfile:
    destfile: /etc/ssl/openssl.cnf
    regexp: 'subjectAltName ='
    line: 'subjectAltName = IP: {{ elk_ip }}'
# Generate SSL certificates for Logstash
- name: Generate SSL certificates
  shell: "openssl req -config /etc/ssl/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout /etc/pki/tls/private/logstash-forwarder.key -out /etc/pki/tls/certs/logstash-forwarder.crt"


#- name: Configure External Beats configuration file
  #template:
  #  src: external-filebeats-input.conf.j2
  #  dest: /etc/logstash/conf.d/02-external-beats-input.conf
  #  owner: root
  #  group: root
  #  mode: 0644

- name: Configure Internal Beats configuration file
  template:
    src: internal-filebeats-input.conf.j2
    dest: /etc/logstash/conf.d/03-internal-beats-input.conf
    owner: root
    group: root
    mode: 0644

- name: Configure Syslog Filter
  template:
    src: syslog-filter.conf.j2
    dest: /etc/logstash/conf.d/10-syslog-filter.conf
    owner: root
    group: root
    mode: 0644

- name: Configure Elasticsearch output file
  template:
    src: elasticsearch-output.conf.j2
    dest: /etc/logstash/conf.d/30-elasticsearch-output.conf
    owner: root
    group: root
    mode: 0644

- name: Configure InfluxDB output file
  template:
    src: influxdb-output.conf.j2
    dest: /etc/logstash/conf.d/29-influxdb-output.conf
    owner: root
    group: root
    mode: 0644

- name: Configure event metric filter with built-in InfluxDB output file
  template:
    src: event-metric-filter-to-influxdb.conf.j2
    dest: /etc/logstash/conf.d/11-event-metric-filter-to-influxdb.conf
    owner: root
    group: root
    mode: 0644

- name: Install InfluxDB output plugin
  shell: /usr/share/logstash/bin/logstash-plugin install logstash-output-influxdb
  # TODO: Change this to when the plugin isn't installed, not just when logstash isn't installed
  when: logstash_check_deb.rc == 1

- name: Start Logstash service
  systemd:
    name: logstash
    state: restarted
    enabled: yes
    

