---
- name: Update repositories cache and install Elasticsearch
  apt:
    name: elasticsearch
    update_cache: yes

# Update Elasticsearch config file to only allow localhost connections
- name: Updating the config file to restrict outside access
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: localhost'

- name: Ensure ES starts at boot
  shell: systemctl enable elasticsearch.service
  
# Restart Elasticsearch
- name: Restarting Elasticsearch
  service:
    name: elasticsearch
    state: restarted