---
- name: Update repositories cache and install Kibana
  apt:
    name: kibana
    update_cache: yes

# Update kibana config file to only accept local connections and use nginx
- name: Config for Nginx reverse proxy
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    force: yes

# Start Kibana service
- name: Starting Kibana service
  systemd:
    name: kibana
    enabled: yes
    state: restarted