---
- name: Add PPA for Nginx
  apt_repository:
    repo: 'ppa:nginx/stable'
    state: present
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

# Deploy kibana.conf with FQDN
- name: Setup Nginx reverse proxy for kibana
  template:
    src: sites.conf.j2
    dest: /etc/nginx/sites-enabled/elk-tick-demo.conf
    force: yes
    owner: root
    group: root
    mode: 0644

# Install Pexpect to handle promts of the terminal
- name: Installing Python Pexpect
  apt:
    name: python-pexpect
    update_cache: yes

- name: Create kibana admin user
  template:
    src: kibanaAdmin.j2
    dest: /tmp/createUser
    owner: root
    group: root
    mode: 0744

- name: Create Kibana admin user
  expect:
     command: bash /tmp/createUser
     responses:
       'Password:' : "{{kibana_password}}"

- name: Restart Nginx service
  service:
    name: nginx
    state: restarted
    enabled: yes