---
- name: Check if InfluxDB is already installed
  command: dpkg-query -W influxdb
  register: influxdb_check_deb
  failed_when: influxdb_check_deb.rc > 1
  changed_when: influxdb_check_deb.rc == 1

- name: Download InfluxDB
  get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.2.4_amd64.deb
    dest: /opt/influxdb_1.2.4_amd64.deb
    mode: 0440
  when: influxdb_check_deb.rc == 1

- name: Install InfluxDB
  apt: 
    deb: '/opt/influxdb_1.2.4_amd64.deb'
  when: influxdb_check_deb.rc == 1

- name: Restarting InfluxDB
  service:
    name: influxdb
    state: restarted
    enabled: yes
